# Generated by Django 3.1 on 2020-09-11 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200911_0850'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryListing',
            new_name='RelationshipsOfCategories',
        ),
    ]
