# Generated by Django 3.1 on 2020-09-11 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200911_0856'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelationshipsOfCategories',
            new_name='CategoriesOfRelationship',
        ),
    ]
