# Generated by Django 3.1 on 2020-09-11 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200911_0902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriesofrelationship',
            options={'verbose_name': 'Relationship of categories', 'verbose_name_plural': 'Relationship of categories'},
        ),
    ]
