# Generated by Django 3.1 on 2020-09-11 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200911_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorylisting',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='categorylisting',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='winner',
            old_name='listing_id',
            new_name='listing',
        ),
    ]
